name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - uses: c-hive/gha-yarn-cache@v1

    - name: Install JS dependencies
      run: yarn install
    
    - name: Change Directory
      run: cd ./android
      
    - name: Display Directory
      run: ls -al
      
    - name: Change wrapper permissions
      run: chmod +x ./android/gradlew

    - run: ./android/gradlew assembleDebug -Dorg.gradle.logging.level=info
      working-directory: android
      name: Build Android apk (debug)

    - uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: '**/*.apk'
